version: '3.3'
services:
  pull:
    container_name: pull
    hostname: pull
    image: pull
    ports:
      - 8080:8080
    entrypoint: ["java", "-jar", "pull-0.0.1-SNAPSHOT.jar"]
    expose:
      - 8080
    environment:
      - spring.datasource.url=jdbc:postgresql://pull-db:5432/pull
    restart: always
    links:
      - pull-db
  pull-db:
    container_name: pull-db
    hostname: pull-db
    image: pull-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pull
    restart: always