version: '3.3'
services:
  survey:
    container_name: survey
    hostname: survey
    image: survey
    ports:
      - 8111:8111
    entrypoint: [ "java", "-jar", "survey-0.0.1-SNAPSHOT.jar" ]
    expose:
      - 8111
    environment:
      - spring.datasource.url=jdbc:postgresql://survey-db:5432/survey
    restart: always
    links:
      - survey-db
  survey-db:
    container_name: survey-db
    hostname: survey-db
    image: survey-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=survey
    restart: always