drop table if exists pull, item, fill_item, fill_item_answer,
    fill_pull, fill_pull_fill_items, pull_items, item_answer,
    usr, user_roles cascade;

create table pull
(
    id          bigint not null generated by default as identity,
    begin_date  date,
    description varchar(255),
    end_date    date,
    is_active   boolean,
    primary key (id)
);
create table fill_pull
(
    id             bigint not null generated by default as identity,
    begin_date     date,
    description    varchar(255),
    end_date       date,
    interviewer_id bigint,
    source_pull_id bigint,
    primary key (id)
);
create table item
(
    id       bigint not null generated by default as identity,
    question varchar(255),
    type     varchar(255),
    primary key (id)
);
create table fill_item
(
    id       bigint not null generated by default as identity,
    question varchar(255),
    type     varchar(255),
    primary key (id)
);
create table fill_item_answer
(
    fill_item_id bigint       not null,
    answer       boolean,
    answer_key   varchar(255) not null,
    constraint fk_fill_item_answer
        foreign key (fill_item_id)
            references fill_item,
    primary key (fill_item_id, answer_key)
);
create table fill_pull_fill_items
(
    fill_pull_id  bigint not null,
    fill_items_id bigint not null,
    constraint fk_fill_pull_fill_items_fill_pull_id
        foreign key (fill_pull_id)
            references fill_pull,
    constraint uk_fill_pull_fill_items_fill_items_id
        unique (fill_items_id),
    constraint fk_fill_pull_fill_items_fill_items_id
        foreign key (fill_items_id)
            references fill_item
);
create table pull_items
(
    pull_id  bigint not null,
    items_id bigint not null,
    constraint fk_pull_items_pull_id
        foreign key (pull_id)
            references pull,
    constraint uk_pull_items_items_id
        unique (items_id),
    constraint fk_pull_items_items_id
        foreign key (items_id)
            references item
);
create table item_answer
(
    item_id    bigint       not null,
    answer     boolean,
    answer_key varchar(255) not null,
    constraint fk_item_answer_item_id
        foreign key (item_id)
            references item,
    primary key (item_id, answer_key)
);
create table usr
(
    id        bigint not null generated by default as identity,
    is_active boolean,
    password  varchar(255),
    user_name varchar(255),
    primary key (id)
);
create table user_roles
(
    user_id bigint not null,
    roles   varchar(255),
    constraint fk_user_roles_user_id
        foreign key (user_id)
            references usr
);

insert into usr (is_active, password, user_name)
values (true,
        'admin',
        'admin');
insert into user_roles (user_id, roles)
values (1,
        'ADMIN');
insert into item (question, type)
values ('Сколько часов в сутках?',
        'SIMPLE_STRING'),
       ('Столица Татарстана?',
        'SINGLE_OPTION'),
       ('Выберите зимние виды спорта?',
        'MULTI_OPTION'),
       ('Сколько часовых поясов В России?',
        'SIMPLE_STRING'),
       ('Столица Татарстана?',
        'SINGLE_OPTION'),
       ('Выберите летние виды спорта',
        'MULTI_OPTION');
insert into item_answer (item_id, answer_key, answer)
values (4,
        '11 часовых поясов',
        false),
       (5,
        'Казань',
        true),
       (5,
        'Набережные Челны',
        false),
       (5,
        'Уфа',
        false),
       (6,
        'Бадминтон',
        true),
       (6,
        'Воллейбол',
        true),
       (6,
        'Лыжные гонки',
        false),
       (6,
        'Биатлон',
        false);
insert into pull (begin_date, description, end_date, is_active)
values ('2022-01-01',
        'Не активный опрос',
        '2022-12-31',
        false),
       ('2022-01-01',
        'Активный опрос',
        '2022-12-31',
        true);
insert into pull_items (pull_id, items_id)
values (1,
        1),
       (1,
        2),
       (1,
        3),
       (2,
        4),
       (2,
        5),
       (2,
        6);
insert into fill_pull (begin_date,
                       description,
                       end_date,
                       interviewer_id,
                       source_pull_id)
values ('2022-01-01',
        'Первый заполненный опрос',
        '2022-12-31',
        1,
        1);
insert into fill_item (question, type)
values ('Сколько часов в сутках?',
        'SIMPLE_STRING'),
       ('Столица Татарстана?',
        'SINGLE_OPTION'),
       ('Выберите зимние виды спорта?',
        'MULTI_OPTION');
insert into fill_item_answer (fill_item_id, answer, answer_key)
values (1,
        false,
        '24 часа'),
       (2,
        true,
        'Казань'),
       (2,
        false,
        'Набережные Челны'),
       (2,
        false,
        'Уфа'),
       (3,
        false,
        'Бадминтон'),
       (3,
        false,
        'Воллейбол'),
       (3,
        true,
        'Лыжные гонки'),
       (3,
        true,
        'Биатлон');
insert into fill_pull_fill_items (fill_pull_id, fill_items_id)
values (1,
        1),
       (1,
        2),
       (1,
        3);